#index:
#    path: /
#    controller: App\Controller\DefaultController::index

conditions:
  path: /conditions
  controller: App\Controller\FrontController::conditions

questions:
  path: /questions
  controller: App\Controller\FrontController